version: 0.1
   
phases:
  build:
    commands:
      - npm install
      - echo " Lint"
      - echo "Building the Code"
      - npm run-script build
artifacts:
  files:
    - build/**/*
    - appspecs.yml
  discard-paths: yes        