version: 0.1
   
phases:
  build:
    commands:
      - yarn
      - yarn cache dir
      - echo " Lint"
      - yarn lint
#      - echo " Test "
#      - yarn test 
      - echo "Building the Code"
      - yarn build       